model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: "val/rec_loss"
    embed_dim: 64
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 20001
        kl_weight: 0.000001
        disc_weight: 0.5

    ddconfig:
      double_z: True
      z_channels: 64
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16,8]
      dropout: 0.0
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    wrap: True
    train:
      target: ldm.data.mead.MeadDataset
      params:
        json_path: ./data/utils/mead_split.json
        base_path: /home/k8suser/hdd1/MEAD_EXTRACTED
        n_fold: 1
        training: True
    validation:
      target: ldm.data.mead.MeadDataset
      params:
        json_path: ./data/utils/mead_split.json
        base_path: /home/k8suser/hdd1/MEAD_EXTRACTED
        n_fold: 1
        training: False

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: True

  trainer:
    benchmark: True
    # accumulate_grad_batches: 2