model:
  base_learning_rate: 4.5e-6
  target: ldm.modules.vitvq3d.models.vitae.Vit_VQ_Trainer
  params:
    # modalities: ['t1', 't1ce', 't2', 'flair']
    # ckpt_path: ./weights/last.ckpt # to be filled
    monitor: val/rec_loss
    modelconfig:
      target: ldm.modules.vitvq3d.models.vitae.ViT_VQ_Model
      params: 
        # embed_dim: 3
        # n_embed: 8192
        # ddconfig:
        #   double_z: False
        #   z_channels: 3
        #   resolution: 192 
        #   in_channels: 1
        #   out_ch: 1
        #   ch: 128
        #   ch_mult:
        #   - 1
        #   - 2
        #   - 4
        #   num_res_blocks: 2
        #   attn_resolutions: []
        #   dropout: 0.0
        n_embed: 8192
        embed_dim: 3
        img_size: 
          - 80
          - 80
          - 64
        patch_size: 16
        enc_dec_embed_dim: 768
        encoder_depth: 12
        encoder_num_heads: 8
        decoder_depth: 8
        as_feature_extractor: false
        decoder_num_heads: 6
        
        mlp_hidden_dim: 1024
        qkv_bias: true
        qk_scale: null
        drop_rate: 0.0
        attn_drop_rate: 0.0
        norm_layer: LayerNorm
        init_values: 0.0
    lossconfig:
      target: ldm.modules.losses.vqperceptual.VQLPIPS3DWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 1
        disc_start: 0
        disc_weight: 0.8
        codebook_weight: 1.0
        perceptual_loss: Null
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 8
    wrap: false
    train:
      target: ldm.data.brats.BratsDataset
      params:
        data_path: D:\Datasets\BraTS2020\BraTS2020_TrainingData\MICCAI_BraTS2020_TrainingData # to be filled
        crop_size: #h,w,d
          - 80
          - 80
          - 64
    validation:
      target: ldm.data.brats.BratsDataset
      params:
        data_path: D:\Datasets\BraTS2020\BraTS2020_ValidationData\MICCAI_BraTS2020_ValidationData # to be filled
        crop_size: #h,w,d
          - 80
          - 80
          - 64

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 300
        max_images: 8
        increase_log_steps: False
        rescale: False
  default_logger: csvlogger
  trainer:
    benchmark: True
    # precision: 16-mixed
    max_epochs: 600
